--- #YAML:1.0
name:               Text-Ngramize
version:            1.03
abstract:           Computes lists of n-grams of text.
author:
    - Jeff Kubina (jeff.kubina@gmail.com)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:  1.14
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
